version: 2

builds:
  - id: mockserver
    main: ./cmd/rmq-rpc-mockserver
    binary: rmq-rpc-mockserver
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitHash={{.Commit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

dockers_v2:
  - id: mockserver
    dockerfile: goreleaser.Dockerfile
    ids:
      - mockserver

    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"

    tags:
      - "{{ .Version }}"
      - latest

    platforms:
      - linux/amd64
      - linux/arm64

    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

    # optional "pull" behavior (GoReleaser expects flags with '=')
    flags:
      - "--pull=true"
