// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: mockserver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AmqpMockServerService_CreateExpectation_FullMethodName    = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/CreateExpectation"
	AmqpMockServerService_GetAssertions_FullMethodName        = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/GetAssertions"
	AmqpMockServerService_GetExpectations_FullMethodName      = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/GetExpectations"
	AmqpMockServerService_GetExpectation_FullMethodName       = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/GetExpectation"
	AmqpMockServerService_ResetExpectations_FullMethodName    = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/ResetExpectations"
	AmqpMockServerService_AddSubscription_FullMethodName      = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/AddSubscription"
	AmqpMockServerService_DeleteSubscription_FullMethodName   = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/DeleteSubscription"
	AmqpMockServerService_UnsubscribeFromQueue_FullMethodName = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/UnsubscribeFromQueue"
	AmqpMockServerService_GetAllSubscriptions_FullMethodName  = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/GetAllSubscriptions"
	AmqpMockServerService_ResetSubscriptions_FullMethodName   = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/ResetSubscriptions"
	AmqpMockServerService_ResetAll_FullMethodName             = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/ResetAll"
	AmqpMockServerService_GetVersion_FullMethodName           = "/rmqrpc.mockserver.api.v1.AmqpMockServerService/GetVersion"
)

// AmqpMockServerServiceClient is the client API for AmqpMockServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AmqpMockServerServiceClient interface {
	// CreateExpectation creates an expectation for a request.
	// This allows mocking third-party services for testing purposes by defining expected requests
	// and the corresponding responses.
	CreateExpectation(ctx context.Context, in *CreateExpectationRequest, opts ...grpc.CallOption) (*CreateExpectationResponse, error)
	// GetAssertions retrieves a list of all historical assertions.
	GetAssertions(ctx context.Context, in *GetAssertionsRequest, opts ...grpc.CallOption) (*GetAssertionsResponse, error)
	// GetAllExpectations retrieves a list of all active expectations.
	GetExpectations(ctx context.Context, in *GetExpectationsRequest, opts ...grpc.CallOption) (*GetExpectationsResponse, error)
	// GetExpectation retrieves a specific expectation by its ID.
	GetExpectation(ctx context.Context, in *GetExpectationRequest, opts ...grpc.CallOption) (*GetExpectationResponse, error)
	// ResetExpectations resets all expectations, effectively removing all mock configurations.
	// Use this to clear existing expectations when starting a new test cycle.
	ResetExpectations(ctx context.Context, in *ResetExpectationsRequest, opts ...grpc.CallOption) (*ResetExpectationsResponse, error)
	// AddSubscription subscribes to an existing RabbitMQ queue.
	// This allows the mockserver to receive requests from specific queues.
	// IMPORTANT: This method does not create a queue, it only subscribes to an existing one.
	AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*AddSubscriptionResponse, error)
	// DeleteSubscription removes a subscription from a queue by subscription ID.
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	// UnsubscribeFromQueue unsubscribes from all subscriptions related to a specific queue.
	UnsubscribeFromQueue(ctx context.Context, in *UnsubscribeFromQueueRequest, opts ...grpc.CallOption) (*UnsubscribeFromQueueResponse, error)
	// GetAllSubscriptions retrieves a list of all active subscriptions.
	GetAllSubscriptions(ctx context.Context, in *GetAllSubscriptionsRequest, opts ...grpc.CallOption) (*GetAllSubscriptionsResponse, error)
	// ResetSubscriptions unsubscribes the mockserver from all queues.
	ResetSubscriptions(ctx context.Context, in *ResetSubscriptionsRequest, opts ...grpc.CallOption) (*ResetSubscriptionsResponse, error)
	// ResetAll resets both expectations and subscriptions, bringing the mockserver to its initial state.
	ResetAll(ctx context.Context, in *ResetAllRequest, opts ...grpc.CallOption) (*ResetAllResponse, error)
	// GetVersion returns the version information of the mockserver application.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type amqpMockServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAmqpMockServerServiceClient(cc grpc.ClientConnInterface) AmqpMockServerServiceClient {
	return &amqpMockServerServiceClient{cc}
}

func (c *amqpMockServerServiceClient) CreateExpectation(ctx context.Context, in *CreateExpectationRequest, opts ...grpc.CallOption) (*CreateExpectationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExpectationResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_CreateExpectation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) GetAssertions(ctx context.Context, in *GetAssertionsRequest, opts ...grpc.CallOption) (*GetAssertionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssertionsResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_GetAssertions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) GetExpectations(ctx context.Context, in *GetExpectationsRequest, opts ...grpc.CallOption) (*GetExpectationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpectationsResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_GetExpectations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) GetExpectation(ctx context.Context, in *GetExpectationRequest, opts ...grpc.CallOption) (*GetExpectationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpectationResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_GetExpectation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) ResetExpectations(ctx context.Context, in *ResetExpectationsRequest, opts ...grpc.CallOption) (*ResetExpectationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetExpectationsResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_ResetExpectations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*AddSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSubscriptionResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_AddSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_DeleteSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) UnsubscribeFromQueue(ctx context.Context, in *UnsubscribeFromQueueRequest, opts ...grpc.CallOption) (*UnsubscribeFromQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeFromQueueResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_UnsubscribeFromQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) GetAllSubscriptions(ctx context.Context, in *GetAllSubscriptionsRequest, opts ...grpc.CallOption) (*GetAllSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSubscriptionsResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_GetAllSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) ResetSubscriptions(ctx context.Context, in *ResetSubscriptionsRequest, opts ...grpc.CallOption) (*ResetSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetSubscriptionsResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_ResetSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) ResetAll(ctx context.Context, in *ResetAllRequest, opts ...grpc.CallOption) (*ResetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetAllResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_ResetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amqpMockServerServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, AmqpMockServerService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmqpMockServerServiceServer is the server API for AmqpMockServerService service.
// All implementations must embed UnimplementedAmqpMockServerServiceServer
// for forward compatibility.
type AmqpMockServerServiceServer interface {
	// CreateExpectation creates an expectation for a request.
	// This allows mocking third-party services for testing purposes by defining expected requests
	// and the corresponding responses.
	CreateExpectation(context.Context, *CreateExpectationRequest) (*CreateExpectationResponse, error)
	// GetAssertions retrieves a list of all historical assertions.
	GetAssertions(context.Context, *GetAssertionsRequest) (*GetAssertionsResponse, error)
	// GetAllExpectations retrieves a list of all active expectations.
	GetExpectations(context.Context, *GetExpectationsRequest) (*GetExpectationsResponse, error)
	// GetExpectation retrieves a specific expectation by its ID.
	GetExpectation(context.Context, *GetExpectationRequest) (*GetExpectationResponse, error)
	// ResetExpectations resets all expectations, effectively removing all mock configurations.
	// Use this to clear existing expectations when starting a new test cycle.
	ResetExpectations(context.Context, *ResetExpectationsRequest) (*ResetExpectationsResponse, error)
	// AddSubscription subscribes to an existing RabbitMQ queue.
	// This allows the mockserver to receive requests from specific queues.
	// IMPORTANT: This method does not create a queue, it only subscribes to an existing one.
	AddSubscription(context.Context, *AddSubscriptionRequest) (*AddSubscriptionResponse, error)
	// DeleteSubscription removes a subscription from a queue by subscription ID.
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	// UnsubscribeFromQueue unsubscribes from all subscriptions related to a specific queue.
	UnsubscribeFromQueue(context.Context, *UnsubscribeFromQueueRequest) (*UnsubscribeFromQueueResponse, error)
	// GetAllSubscriptions retrieves a list of all active subscriptions.
	GetAllSubscriptions(context.Context, *GetAllSubscriptionsRequest) (*GetAllSubscriptionsResponse, error)
	// ResetSubscriptions unsubscribes the mockserver from all queues.
	ResetSubscriptions(context.Context, *ResetSubscriptionsRequest) (*ResetSubscriptionsResponse, error)
	// ResetAll resets both expectations and subscriptions, bringing the mockserver to its initial state.
	ResetAll(context.Context, *ResetAllRequest) (*ResetAllResponse, error)
	// GetVersion returns the version information of the mockserver application.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	mustEmbedUnimplementedAmqpMockServerServiceServer()
}

// UnimplementedAmqpMockServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAmqpMockServerServiceServer struct{}

func (UnimplementedAmqpMockServerServiceServer) CreateExpectation(context.Context, *CreateExpectationRequest) (*CreateExpectationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExpectation not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) GetAssertions(context.Context, *GetAssertionsRequest) (*GetAssertionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssertions not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) GetExpectations(context.Context, *GetExpectationsRequest) (*GetExpectationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpectations not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) GetExpectation(context.Context, *GetExpectationRequest) (*GetExpectationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpectation not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) ResetExpectations(context.Context, *ResetExpectationsRequest) (*ResetExpectationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetExpectations not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) AddSubscription(context.Context, *AddSubscriptionRequest) (*AddSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSubscription not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) UnsubscribeFromQueue(context.Context, *UnsubscribeFromQueueRequest) (*UnsubscribeFromQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeFromQueue not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) GetAllSubscriptions(context.Context, *GetAllSubscriptionsRequest) (*GetAllSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSubscriptions not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) ResetSubscriptions(context.Context, *ResetSubscriptionsRequest) (*ResetSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetSubscriptions not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) ResetAll(context.Context, *ResetAllRequest) (*ResetAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetAll not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedAmqpMockServerServiceServer) mustEmbedUnimplementedAmqpMockServerServiceServer() {}
func (UnimplementedAmqpMockServerServiceServer) testEmbeddedByValue()                               {}

// UnsafeAmqpMockServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmqpMockServerServiceServer will
// result in compilation errors.
type UnsafeAmqpMockServerServiceServer interface {
	mustEmbedUnimplementedAmqpMockServerServiceServer()
}

func RegisterAmqpMockServerServiceServer(s grpc.ServiceRegistrar, srv AmqpMockServerServiceServer) {
	// If the following call panics, it indicates UnimplementedAmqpMockServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AmqpMockServerService_ServiceDesc, srv)
}

func _AmqpMockServerService_CreateExpectation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExpectationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).CreateExpectation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_CreateExpectation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).CreateExpectation(ctx, req.(*CreateExpectationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_GetAssertions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssertionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).GetAssertions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_GetAssertions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).GetAssertions(ctx, req.(*GetAssertionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_GetExpectations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpectationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).GetExpectations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_GetExpectations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).GetExpectations(ctx, req.(*GetExpectationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_GetExpectation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpectationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).GetExpectation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_GetExpectation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).GetExpectation(ctx, req.(*GetExpectationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_ResetExpectations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetExpectationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).ResetExpectations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_ResetExpectations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).ResetExpectations(ctx, req.(*ResetExpectationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_AddSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).AddSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_AddSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).AddSubscription(ctx, req.(*AddSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_UnsubscribeFromQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeFromQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).UnsubscribeFromQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_UnsubscribeFromQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).UnsubscribeFromQueue(ctx, req.(*UnsubscribeFromQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_GetAllSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).GetAllSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_GetAllSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).GetAllSubscriptions(ctx, req.(*GetAllSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_ResetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).ResetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_ResetSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).ResetSubscriptions(ctx, req.(*ResetSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_ResetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).ResetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_ResetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).ResetAll(ctx, req.(*ResetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmqpMockServerService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmqpMockServerServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmqpMockServerService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmqpMockServerServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AmqpMockServerService_ServiceDesc is the grpc.ServiceDesc for AmqpMockServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AmqpMockServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rmqrpc.mockserver.api.v1.AmqpMockServerService",
	HandlerType: (*AmqpMockServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExpectation",
			Handler:    _AmqpMockServerService_CreateExpectation_Handler,
		},
		{
			MethodName: "GetAssertions",
			Handler:    _AmqpMockServerService_GetAssertions_Handler,
		},
		{
			MethodName: "GetExpectations",
			Handler:    _AmqpMockServerService_GetExpectations_Handler,
		},
		{
			MethodName: "GetExpectation",
			Handler:    _AmqpMockServerService_GetExpectation_Handler,
		},
		{
			MethodName: "ResetExpectations",
			Handler:    _AmqpMockServerService_ResetExpectations_Handler,
		},
		{
			MethodName: "AddSubscription",
			Handler:    _AmqpMockServerService_AddSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _AmqpMockServerService_DeleteSubscription_Handler,
		},
		{
			MethodName: "UnsubscribeFromQueue",
			Handler:    _AmqpMockServerService_UnsubscribeFromQueue_Handler,
		},
		{
			MethodName: "GetAllSubscriptions",
			Handler:    _AmqpMockServerService_GetAllSubscriptions_Handler,
		},
		{
			MethodName: "ResetSubscriptions",
			Handler:    _AmqpMockServerService_ResetSubscriptions_Handler,
		},
		{
			MethodName: "ResetAll",
			Handler:    _AmqpMockServerService_ResetAll_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _AmqpMockServerService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mockserver.proto",
}
