// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: mockserver.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JSONBodyAssertion_MatchType int32

const (
	// Unspecified match type. If not set, it defaults to EXACT.
	JSONBodyAssertion_MATCH_TYPE_UNSPECIFIED JSONBodyAssertion_MatchType = 0
	// Exact match of the JSON body.
	JSONBodyAssertion_MATCH_TYPE_EXACT JSONBodyAssertion_MatchType = 1
	// Partial match of the JSON body; only specified fields need to be present.
	JSONBodyAssertion_MATCH_TYPE_PARTIAL JSONBodyAssertion_MatchType = 2
)

// Enum value maps for JSONBodyAssertion_MatchType.
var (
	JSONBodyAssertion_MatchType_name = map[int32]string{
		0: "MATCH_TYPE_UNSPECIFIED",
		1: "MATCH_TYPE_EXACT",
		2: "MATCH_TYPE_PARTIAL",
	}
	JSONBodyAssertion_MatchType_value = map[string]int32{
		"MATCH_TYPE_UNSPECIFIED": 0,
		"MATCH_TYPE_EXACT":       1,
		"MATCH_TYPE_PARTIAL":     2,
	}
)

func (x JSONBodyAssertion_MatchType) Enum() *JSONBodyAssertion_MatchType {
	p := new(JSONBodyAssertion_MatchType)
	*p = x
	return p
}

func (x JSONBodyAssertion_MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JSONBodyAssertion_MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_mockserver_proto_enumTypes[0].Descriptor()
}

func (JSONBodyAssertion_MatchType) Type() protoreflect.EnumType {
	return &file_mockserver_proto_enumTypes[0]
}

func (x JSONBodyAssertion_MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JSONBodyAssertion_MatchType.Descriptor instead.
func (JSONBodyAssertion_MatchType) EnumDescriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{9, 0}
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_mockserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// AddSubscriptionRequest is a request to add a subscription to a queue
type AddSubscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// queue is the name of the queue to subscribe to.
	Queue string `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// idempotent indicates if the subscription should be idempotent.
	// If true, adding a subscription with the same queue name multiple times will result in only one subscription.
	Idempotent    bool `protobuf:"varint,2,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionRequest) Reset() {
	*x = AddSubscriptionRequest{}
	mi := &file_mockserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionRequest) ProtoMessage() {}

func (x *AddSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*AddSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{1}
}

func (x *AddSubscriptionRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *AddSubscriptionRequest) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

// AddSubscriptionResponse returns the newly created subscription.
type AddSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionResponse) Reset() {
	*x = AddSubscriptionResponse{}
	mi := &file_mockserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionResponse) ProtoMessage() {}

func (x *AddSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*AddSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{2}
}

func (x *AddSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// DeleteSubscriptionRequest is a request to remove a subscription from a queue.
type DeleteSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_mockserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// DeleteSubscriptionResponse is returned after a subscription is successfully removed.
type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	mi := &file_mockserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{4}
}

// UnsubscribeFromQueueRequest is used to remove all subscriptions from a specified queue.
type UnsubscribeFromQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeFromQueueRequest) Reset() {
	*x = UnsubscribeFromQueueRequest{}
	mi := &file_mockserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeFromQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeFromQueueRequest) ProtoMessage() {}

func (x *UnsubscribeFromQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeFromQueueRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeFromQueueRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeFromQueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// UnsubscribeFromQueueResponse confirms the successful removal of subscriptions from the queue.
type UnsubscribeFromQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeFromQueueResponse) Reset() {
	*x = UnsubscribeFromQueueResponse{}
	mi := &file_mockserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeFromQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeFromQueueResponse) ProtoMessage() {}

func (x *UnsubscribeFromQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeFromQueueResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeFromQueueResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{6}
}

// GetAllSubscriptionsRequest is used to retrieve all active subscriptions.
type GetAllSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubscriptionsRequest) Reset() {
	*x = GetAllSubscriptionsRequest{}
	mi := &file_mockserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubscriptionsRequest) ProtoMessage() {}

func (x *GetAllSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{7}
}

// GetAllSubscriptionsResponse contains a list of active subscriptions.
type GetAllSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubscriptionsResponse) Reset() {
	*x = GetAllSubscriptionsResponse{}
	mi := &file_mockserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubscriptionsResponse) ProtoMessage() {}

func (x *GetAllSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// JSONBodyAssertion is used to specify matching rules for JSON body content.
type JSONBodyAssertion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON structure to be matched.
	Body *structpb.Struct `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// Type of matching for the JSON body.
	MatchType     JSONBodyAssertion_MatchType `protobuf:"varint,2,opt,name=match_type,json=matchType,proto3,enum=rmqrpc.mockserver.api.v1.JSONBodyAssertion_MatchType" json:"match_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONBodyAssertion) Reset() {
	*x = JSONBodyAssertion{}
	mi := &file_mockserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONBodyAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONBodyAssertion) ProtoMessage() {}

func (x *JSONBodyAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONBodyAssertion.ProtoReflect.Descriptor instead.
func (*JSONBodyAssertion) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{9}
}

func (x *JSONBodyAssertion) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *JSONBodyAssertion) GetMatchType() JSONBodyAssertion_MatchType {
	if x != nil {
		return x.MatchType
	}
	return JSONBodyAssertion_MATCH_TYPE_UNSPECIFIED
}

// RegexBodyAssertion is used to specify matching rules using regular expressions.
type RegexBodyAssertion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// regex is the pattern that should match the body of the request.
	Regex         string `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegexBodyAssertion) Reset() {
	*x = RegexBodyAssertion{}
	mi := &file_mockserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegexBodyAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexBodyAssertion) ProtoMessage() {}

func (x *RegexBodyAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexBodyAssertion.ProtoReflect.Descriptor instead.
func (*RegexBodyAssertion) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{10}
}

func (x *RegexBodyAssertion) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

// Request represents an incoming request that the mockserver should expect.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exchange the message is sent to.
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// The routing key the message is sent with.
	RoutingKey string `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Request_JsonBody
	//	*Request_RegexBody
	Body          isRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_mockserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{11}
}

func (x *Request) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Request) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Request) GetBody() isRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetJsonBody() *JSONBodyAssertion {
	if x != nil {
		if x, ok := x.Body.(*Request_JsonBody); ok {
			return x.JsonBody
		}
	}
	return nil
}

func (x *Request) GetRegexBody() *RegexBodyAssertion {
	if x != nil {
		if x, ok := x.Body.(*Request_RegexBody); ok {
			return x.RegexBody
		}
	}
	return nil
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_JsonBody struct {
	// Match the JSON body of the request.
	JsonBody *JSONBodyAssertion `protobuf:"bytes,3,opt,name=json_body,json=jsonBody,proto3,oneof"`
}

type Request_RegexBody struct {
	// Match the body of the request using a regular expression.
	RegexBody *RegexBodyAssertion `protobuf:"bytes,4,opt,name=regex_body,json=regexBody,proto3,oneof"`
}

func (*Request_JsonBody) isRequest_Body() {}

func (*Request_RegexBody) isRequest_Body() {}

// Response represents a response that the mockserver should return when the expectation is met.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The response body to be returned.
	Body          *structpb.Value `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_mockserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetBody() *structpb.Value {
	if x != nil {
		return x.Body
	}
	return nil
}

// Times represents the number of times an expectation should/can be met
type Times struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Times:
	//
	//	*Times_RemainingTimes
	//	*Times_Unlimited
	Times         isTimes_Times `protobuf_oneof:"times"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Times) Reset() {
	*x = Times{}
	mi := &file_mockserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Times) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Times) ProtoMessage() {}

func (x *Times) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Times.ProtoReflect.Descriptor instead.
func (*Times) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{13}
}

func (x *Times) GetTimes() isTimes_Times {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *Times) GetRemainingTimes() uint32 {
	if x != nil {
		if x, ok := x.Times.(*Times_RemainingTimes); ok {
			return x.RemainingTimes
		}
	}
	return 0
}

func (x *Times) GetUnlimited() bool {
	if x != nil {
		if x, ok := x.Times.(*Times_Unlimited); ok {
			return x.Unlimited
		}
	}
	return false
}

type isTimes_Times interface {
	isTimes_Times()
}

type Times_RemainingTimes struct {
	// remaining_times is the number of times the expectation can be met.
	RemainingTimes uint32 `protobuf:"varint,1,opt,name=remaining_times,json=remainingTimes,proto3,oneof"`
}

type Times_Unlimited struct {
	// unlimited indicates that the expectation can be met an unlimited number of times.
	Unlimited bool `protobuf:"varint,2,opt,name=unlimited,proto3,oneof"`
}

func (*Times_RemainingTimes) isTimes_Times() {}

func (*Times_Unlimited) isTimes_Times() {}

// CreateExpectationRequest is used to define an expectation for an incoming request.
type CreateExpectationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request is the expected request details.
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// response is a response that should be returned when the expectation is met.
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	// times is a number of times the expectation should be met
	// if is not set, the expectation is set to be met once
	Times *Times `protobuf:"bytes,3,opt,name=times,proto3,oneof" json:"times,omitempty"`
	// time_to_live_seconds is a time to live for the expectation in seconds
	// if time_to_live_seconds is not set, then the expectation is set to be live forever
	TimeToLiveSeconds *float32 `protobuf:"fixed32,4,opt,name=time_to_live_seconds,json=timeToLiveSeconds,proto3,oneof" json:"time_to_live_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateExpectationRequest) Reset() {
	*x = CreateExpectationRequest{}
	mi := &file_mockserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpectationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpectationRequest) ProtoMessage() {}

func (x *CreateExpectationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpectationRequest.ProtoReflect.Descriptor instead.
func (*CreateExpectationRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{14}
}

func (x *CreateExpectationRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CreateExpectationRequest) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateExpectationRequest) GetTimes() *Times {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *CreateExpectationRequest) GetTimeToLiveSeconds() float32 {
	if x != nil && x.TimeToLiveSeconds != nil {
		return *x.TimeToLiveSeconds
	}
	return 0
}

// Expectation represents an expectation for an incoming request.
type Expectation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique identifier for the expectation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// request is the expected request details.
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	// response is a response that should be returned when the expectation is met.
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	// times is a number of times the expectation should be met
	Times *Times `protobuf:"bytes,4,opt,name=times,proto3" json:"times,omitempty"`
	// expires_at is a time when the expectation expires
	ExpiresAt *string `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	// created_at is a time when the expectation was created
	CreatedAt     string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expectation) Reset() {
	*x = Expectation{}
	mi := &file_mockserver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expectation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expectation) ProtoMessage() {}

func (x *Expectation) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expectation.ProtoReflect.Descriptor instead.
func (*Expectation) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{15}
}

func (x *Expectation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expectation) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Expectation) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Expectation) GetTimes() *Times {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *Expectation) GetExpiresAt() string {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return ""
}

func (x *Expectation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Assertion represents an assertion for an incoming request.
type Assertion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique identifier for the assertion.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// candidate is a candidate request sent to the mockserver.
	Candidate *Assertion_Candidate `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	// matched is a boolean indicating if the assertion matched an expectation.
	Matched bool `protobuf:"varint,3,opt,name=matched,proto3" json:"matched,omitempty"`
	// expectation is a matched expectation.
	// have value if the assertion is matched and "included" in request is set to embed expectation
	Expectation *Expectation `protobuf:"bytes,4,opt,name=expectation,proto3,oneof" json:"expectation,omitempty"`
	// created_at is a time when the assertion was created.
	CreatedAt     string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_mockserver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{16}
}

func (x *Assertion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Assertion) GetCandidate() *Assertion_Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *Assertion) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *Assertion) GetExpectation() *Expectation {
	if x != nil {
		return x.Expectation
	}
	return nil
}

func (x *Assertion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// GetAssertionsRequest is used to retrieve history of assertions.
type GetAssertionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expectation_id will return only assertions for the given expectation.
	ExpectationId *string `protobuf:"bytes,1,opt,name=expectation_id,json=expectationId,proto3,oneof" json:"expectation_id,omitempty"`
	// status will return only assertions with the given status. by default it returns all assertions.
	Status *string `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"` // matched, unmatched
	// include will return embedded entities related to the assertion.
	Include       []string `protobuf:"bytes,3,rep,name=include,proto3" json:"include,omitempty"` // expectation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssertionsRequest) Reset() {
	*x = GetAssertionsRequest{}
	mi := &file_mockserver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssertionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssertionsRequest) ProtoMessage() {}

func (x *GetAssertionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssertionsRequest.ProtoReflect.Descriptor instead.
func (*GetAssertionsRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{17}
}

func (x *GetAssertionsRequest) GetExpectationId() string {
	if x != nil && x.ExpectationId != nil {
		return *x.ExpectationId
	}
	return ""
}

func (x *GetAssertionsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetAssertionsRequest) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

// GetAssertionsResponse contains a list of assertions.
type GetAssertionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assertions    []*Assertion           `protobuf:"bytes,1,rep,name=assertions,proto3" json:"assertions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssertionsResponse) Reset() {
	*x = GetAssertionsResponse{}
	mi := &file_mockserver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssertionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssertionsResponse) ProtoMessage() {}

func (x *GetAssertionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssertionsResponse.ProtoReflect.Descriptor instead.
func (*GetAssertionsResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{18}
}

func (x *GetAssertionsResponse) GetAssertions() []*Assertion {
	if x != nil {
		return x.Assertions
	}
	return nil
}

// GetExpectationsRequest is used to retrieve all expectations.
type GetExpectationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status will return only expectations with the given status. by default it returns all expectations.
	Status        *string `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"` // active, expired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpectationsRequest) Reset() {
	*x = GetExpectationsRequest{}
	mi := &file_mockserver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpectationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpectationsRequest) ProtoMessage() {}

func (x *GetExpectationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpectationsRequest.ProtoReflect.Descriptor instead.
func (*GetExpectationsRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{19}
}

func (x *GetExpectationsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// GetExpectationsResponse contains a list of expectations.
type GetExpectationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expectations  []*Expectation         `protobuf:"bytes,1,rep,name=expectations,proto3" json:"expectations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpectationsResponse) Reset() {
	*x = GetExpectationsResponse{}
	mi := &file_mockserver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpectationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpectationsResponse) ProtoMessage() {}

func (x *GetExpectationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpectationsResponse.ProtoReflect.Descriptor instead.
func (*GetExpectationsResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{20}
}

func (x *GetExpectationsResponse) GetExpectations() []*Expectation {
	if x != nil {
		return x.Expectations
	}
	return nil
}

// GetExpectationRequest is used to retrieve a specific expectation by its ID.
type GetExpectationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expectation_id is a unique identifier for the expectation.
	ExpectationId string `protobuf:"bytes,1,opt,name=expectation_id,json=expectationId,proto3" json:"expectation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpectationRequest) Reset() {
	*x = GetExpectationRequest{}
	mi := &file_mockserver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpectationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpectationRequest) ProtoMessage() {}

func (x *GetExpectationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpectationRequest.ProtoReflect.Descriptor instead.
func (*GetExpectationRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{21}
}

func (x *GetExpectationRequest) GetExpectationId() string {
	if x != nil {
		return x.ExpectationId
	}
	return ""
}

// GetExpectationResponse contains the requested expectation.
type GetExpectationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expectation   *Expectation           `protobuf:"bytes,1,opt,name=expectation,proto3" json:"expectation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpectationResponse) Reset() {
	*x = GetExpectationResponse{}
	mi := &file_mockserver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpectationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpectationResponse) ProtoMessage() {}

func (x *GetExpectationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpectationResponse.ProtoReflect.Descriptor instead.
func (*GetExpectationResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{22}
}

func (x *GetExpectationResponse) GetExpectation() *Expectation {
	if x != nil {
		return x.Expectation
	}
	return nil
}

// CreateExpectationResponse is a response to CreateExpectationRequest
type CreateExpectationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expectation_id is a unique identifier for the created expectation.
	ExpectationId string `protobuf:"bytes,1,opt,name=expectation_id,json=expectationId,proto3" json:"expectation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpectationResponse) Reset() {
	*x = CreateExpectationResponse{}
	mi := &file_mockserver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpectationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpectationResponse) ProtoMessage() {}

func (x *CreateExpectationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpectationResponse.ProtoReflect.Descriptor instead.
func (*CreateExpectationResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{23}
}

func (x *CreateExpectationResponse) GetExpectationId() string {
	if x != nil {
		return x.ExpectationId
	}
	return ""
}

// ResetExpectationsRequest is used to reset all expectations.
type ResetExpectationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetExpectationsRequest) Reset() {
	*x = ResetExpectationsRequest{}
	mi := &file_mockserver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetExpectationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetExpectationsRequest) ProtoMessage() {}

func (x *ResetExpectationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetExpectationsRequest.ProtoReflect.Descriptor instead.
func (*ResetExpectationsRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{24}
}

// ResetExpectationsResponse is returned after all expectations are successfully reset.
type ResetExpectationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetExpectationsResponse) Reset() {
	*x = ResetExpectationsResponse{}
	mi := &file_mockserver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetExpectationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetExpectationsResponse) ProtoMessage() {}

func (x *ResetExpectationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetExpectationsResponse.ProtoReflect.Descriptor instead.
func (*ResetExpectationsResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{25}
}

// ResetSubscriptionsRequest is used to reset all subscriptions.
type ResetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSubscriptionsRequest) Reset() {
	*x = ResetSubscriptionsRequest{}
	mi := &file_mockserver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSubscriptionsRequest) ProtoMessage() {}

func (x *ResetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ResetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{26}
}

// ResetSubscriptionsResponse is returned after all subscriptions are successfully reset.
type ResetSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSubscriptionsResponse) Reset() {
	*x = ResetSubscriptionsResponse{}
	mi := &file_mockserver_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSubscriptionsResponse) ProtoMessage() {}

func (x *ResetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ResetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{27}
}

// ResetAllRequest is used to reset both expectations and subscriptions.
type ResetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllRequest) Reset() {
	*x = ResetAllRequest{}
	mi := &file_mockserver_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllRequest) ProtoMessage() {}

func (x *ResetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllRequest.ProtoReflect.Descriptor instead.
func (*ResetAllRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{28}
}

// ResetAllResponse is returned after both expectations and subscriptions are successfully reset.
type ResetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllResponse) Reset() {
	*x = ResetAllResponse{}
	mi := &file_mockserver_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllResponse) ProtoMessage() {}

func (x *ResetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllResponse.ProtoReflect.Descriptor instead.
func (*ResetAllResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{29}
}

// GetVersionRequest is used to retrieve the version information of the mockserver application.
type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_mockserver_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{30}
}

// GetVersionResponse contains the version information of the mockserver application.
type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the semantic version of the mockserver application.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// commit_hash is the commit hash of the mockserver application.
	CommitHash string `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	// build_date is the date the mockserver application was built.
	BuildDate     string `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_mockserver_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{31}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *GetVersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

// Candidate represents a candidate request sent to the mockserver.
type Assertion_Candidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exchange the message is sent to.
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// The routing key the message is sent with.
	RoutingKey string `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// The candidate JSON structure to be matched.
	Body          *structpb.Struct `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertion_Candidate) Reset() {
	*x = Assertion_Candidate{}
	mi := &file_mockserver_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion_Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion_Candidate) ProtoMessage() {}

func (x *Assertion_Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion_Candidate.ProtoReflect.Descriptor instead.
func (*Assertion_Candidate) Descriptor() ([]byte, []int) {
	return file_mockserver_proto_rawDescGZIP(), []int{16, 0}
}

func (x *Assertion_Candidate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Assertion_Candidate) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Assertion_Candidate) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_mockserver_proto protoreflect.FileDescriptor

const file_mockserver_proto_rawDesc = "" +
	"\n" +
	"\x10mockserver.proto\x12\x18rmqrpc.mockserver.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"4\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\"N\n" +
	"\x16AddSubscriptionRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x02 \x01(\bR\n" +
	"idempotent\"e\n" +
	"\x17AddSubscriptionResponse\x12J\n" +
	"\fsubscription\x18\x01 \x01(\v2&.rmqrpc.mockserver.api.v1.SubscriptionR\fsubscription\"D\n" +
	"\x19DeleteSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"\x1c\n" +
	"\x1aDeleteSubscriptionResponse\"3\n" +
	"\x1bUnsubscribeFromQueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\x1e\n" +
	"\x1cUnsubscribeFromQueueResponse\"\x1c\n" +
	"\x1aGetAllSubscriptionsRequest\"k\n" +
	"\x1bGetAllSubscriptionsResponse\x12L\n" +
	"\rsubscriptions\x18\x01 \x03(\v2&.rmqrpc.mockserver.api.v1.SubscriptionR\rsubscriptions\"\xed\x01\n" +
	"\x11JSONBodyAssertion\x12+\n" +
	"\x04body\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04body\x12T\n" +
	"\n" +
	"match_type\x18\x02 \x01(\x0e25.rmqrpc.mockserver.api.v1.JSONBodyAssertion.MatchTypeR\tmatchType\"U\n" +
	"\tMatchType\x12\x1a\n" +
	"\x16MATCH_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MATCH_TYPE_EXACT\x10\x01\x12\x16\n" +
	"\x12MATCH_TYPE_PARTIAL\x10\x02\"*\n" +
	"\x12RegexBodyAssertion\x12\x14\n" +
	"\x05regex\x18\x01 \x01(\tR\x05regex\"\xe9\x01\n" +
	"\aRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12J\n" +
	"\tjson_body\x18\x03 \x01(\v2+.rmqrpc.mockserver.api.v1.JSONBodyAssertionH\x00R\bjsonBody\x12M\n" +
	"\n" +
	"regex_body\x18\x04 \x01(\v2,.rmqrpc.mockserver.api.v1.RegexBodyAssertionH\x00R\tregexBodyB\x06\n" +
	"\x04body\"6\n" +
	"\bResponse\x12*\n" +
	"\x04body\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04body\"[\n" +
	"\x05Times\x12)\n" +
	"\x0fremaining_times\x18\x01 \x01(\rH\x00R\x0eremainingTimes\x12\x1e\n" +
	"\tunlimited\x18\x02 \x01(\bH\x00R\tunlimitedB\a\n" +
	"\x05times\"\xac\x02\n" +
	"\x18CreateExpectationRequest\x12;\n" +
	"\arequest\x18\x01 \x01(\v2!.rmqrpc.mockserver.api.v1.RequestR\arequest\x12>\n" +
	"\bresponse\x18\x02 \x01(\v2\".rmqrpc.mockserver.api.v1.ResponseR\bresponse\x12:\n" +
	"\x05times\x18\x03 \x01(\v2\x1f.rmqrpc.mockserver.api.v1.TimesH\x00R\x05times\x88\x01\x01\x124\n" +
	"\x14time_to_live_seconds\x18\x04 \x01(\x02H\x01R\x11timeToLiveSeconds\x88\x01\x01B\b\n" +
	"\x06_timesB\x17\n" +
	"\x15_time_to_live_seconds\"\xa3\x02\n" +
	"\vExpectation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\arequest\x18\x02 \x01(\v2!.rmqrpc.mockserver.api.v1.RequestR\arequest\x12>\n" +
	"\bresponse\x18\x03 \x01(\v2\".rmqrpc.mockserver.api.v1.ResponseR\bresponse\x125\n" +
	"\x05times\x18\x04 \x01(\v2\x1f.rmqrpc.mockserver.api.v1.TimesR\x05times\x12\"\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tH\x00R\texpiresAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\r\n" +
	"\v_expires_at\"\xf6\x02\n" +
	"\tAssertion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\tcandidate\x18\x02 \x01(\v2-.rmqrpc.mockserver.api.v1.Assertion.CandidateR\tcandidate\x12\x18\n" +
	"\amatched\x18\x03 \x01(\bR\amatched\x12L\n" +
	"\vexpectation\x18\x04 \x01(\v2%.rmqrpc.mockserver.api.v1.ExpectationH\x00R\vexpectation\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x1au\n" +
	"\tCandidate\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12+\n" +
	"\x04body\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04bodyB\x0e\n" +
	"\f_expectation\"\x97\x01\n" +
	"\x14GetAssertionsRequest\x12*\n" +
	"\x0eexpectation_id\x18\x01 \x01(\tH\x00R\rexpectationId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x18\n" +
	"\ainclude\x18\x03 \x03(\tR\aincludeB\x11\n" +
	"\x0f_expectation_idB\t\n" +
	"\a_status\"\\\n" +
	"\x15GetAssertionsResponse\x12C\n" +
	"\n" +
	"assertions\x18\x01 \x03(\v2#.rmqrpc.mockserver.api.v1.AssertionR\n" +
	"assertions\"@\n" +
	"\x16GetExpectationsRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"d\n" +
	"\x17GetExpectationsResponse\x12I\n" +
	"\fexpectations\x18\x01 \x03(\v2%.rmqrpc.mockserver.api.v1.ExpectationR\fexpectations\">\n" +
	"\x15GetExpectationRequest\x12%\n" +
	"\x0eexpectation_id\x18\x01 \x01(\tR\rexpectationId\"a\n" +
	"\x16GetExpectationResponse\x12G\n" +
	"\vexpectation\x18\x01 \x01(\v2%.rmqrpc.mockserver.api.v1.ExpectationR\vexpectation\"B\n" +
	"\x19CreateExpectationResponse\x12%\n" +
	"\x0eexpectation_id\x18\x01 \x01(\tR\rexpectationId\"\x1a\n" +
	"\x18ResetExpectationsRequest\"\x1b\n" +
	"\x19ResetExpectationsResponse\"\x1b\n" +
	"\x19ResetSubscriptionsRequest\"\x1c\n" +
	"\x1aResetSubscriptionsResponse\"\x11\n" +
	"\x0fResetAllRequest\"\x12\n" +
	"\x10ResetAllResponse\"\x13\n" +
	"\x11GetVersionRequest\"n\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate2\x8f\x0f\n" +
	"\x15AmqpMockServerService\x12\x9d\x01\n" +
	"\x11CreateExpectation\x122.rmqrpc.mockserver.api.v1.CreateExpectationRequest\x1a3.rmqrpc.mockserver.api.v1.CreateExpectationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/expectations\x12\x8c\x01\n" +
	"\rGetAssertions\x12..rmqrpc.mockserver.api.v1.GetAssertionsRequest\x1a/.rmqrpc.mockserver.api.v1.GetAssertionsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/assertions\x12\x94\x01\n" +
	"\x0fGetExpectations\x120.rmqrpc.mockserver.api.v1.GetExpectationsRequest\x1a1.rmqrpc.mockserver.api.v1.GetExpectationsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/expectations\x12\xaf\x01\n" +
	"\x0eGetExpectation\x12/.rmqrpc.mockserver.api.v1.GetExpectationRequest\x1a0.rmqrpc.mockserver.api.v1.GetExpectationResponse\":\x82\xd3\xe4\x93\x024b\vexpectation\x12%/api/v1/expectations/{expectation_id}\x12\x9a\x01\n" +
	"\x11ResetExpectations\x122.rmqrpc.mockserver.api.v1.ResetExpectationsRequest\x1a3.rmqrpc.mockserver.api.v1.ResetExpectationsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/expectations\x12\xa6\x01\n" +
	"\x0fAddSubscription\x120.rmqrpc.mockserver.api.v1.AddSubscriptionRequest\x1a1.rmqrpc.mockserver.api.v1.AddSubscriptionResponse\".\x82\xd3\xe4\x93\x02(:\x01*b\fsubscription\"\x15/api/v1/subscriptions\x12\xb0\x01\n" +
	"\x12DeleteSubscription\x123.rmqrpc.mockserver.api.v1.DeleteSubscriptionRequest\x1a4.rmqrpc.mockserver.api.v1.DeleteSubscriptionResponse\"/\x82\xd3\xe4\x93\x02)*'/api/v1/subscriptions/{subscription_id}\x12\xb3\x01\n" +
	"\x14UnsubscribeFromQueue\x125.rmqrpc.mockserver.api.v1.UnsubscribeFromQueueRequest\x1a6.rmqrpc.mockserver.api.v1.UnsubscribeFromQueueResponse\",\x82\xd3\xe4\x93\x02&*$/api/v1/subscriptions/queues/{queue}\x12\xb0\x01\n" +
	"\x13GetAllSubscriptions\x124.rmqrpc.mockserver.api.v1.GetAllSubscriptionsRequest\x1a5.rmqrpc.mockserver.api.v1.GetAllSubscriptionsResponse\",\x82\xd3\xe4\x93\x02&b\rsubscriptions\x12\x15/api/v1/subscriptions\x12\x9e\x01\n" +
	"\x12ResetSubscriptions\x123.rmqrpc.mockserver.api.v1.ResetSubscriptionsRequest\x1a4.rmqrpc.mockserver.api.v1.ResetSubscriptionsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/subscriptions\x12x\n" +
	"\bResetAll\x12).rmqrpc.mockserver.api.v1.ResetAllRequest\x1a*.rmqrpc.mockserver.api.v1.ResetAllResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/api/v1/reset\x12\x80\x01\n" +
	"\n" +
	"GetVersion\x12+.rmqrpc.mockserver.api.v1.GetVersionRequest\x1a,.rmqrpc.mockserver.api.v1.GetVersionResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/versionB;Z9github.com/dialecticanet-com/rmq-rpc-mockserver/api/v1;v1b\x06proto3"

var (
	file_mockserver_proto_rawDescOnce sync.Once
	file_mockserver_proto_rawDescData []byte
)

func file_mockserver_proto_rawDescGZIP() []byte {
	file_mockserver_proto_rawDescOnce.Do(func() {
		file_mockserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mockserver_proto_rawDesc), len(file_mockserver_proto_rawDesc)))
	})
	return file_mockserver_proto_rawDescData
}

var file_mockserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mockserver_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_mockserver_proto_goTypes = []any{
	(JSONBodyAssertion_MatchType)(0),     // 0: rmqrpc.mockserver.api.v1.JSONBodyAssertion.MatchType
	(*Subscription)(nil),                 // 1: rmqrpc.mockserver.api.v1.Subscription
	(*AddSubscriptionRequest)(nil),       // 2: rmqrpc.mockserver.api.v1.AddSubscriptionRequest
	(*AddSubscriptionResponse)(nil),      // 3: rmqrpc.mockserver.api.v1.AddSubscriptionResponse
	(*DeleteSubscriptionRequest)(nil),    // 4: rmqrpc.mockserver.api.v1.DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil),   // 5: rmqrpc.mockserver.api.v1.DeleteSubscriptionResponse
	(*UnsubscribeFromQueueRequest)(nil),  // 6: rmqrpc.mockserver.api.v1.UnsubscribeFromQueueRequest
	(*UnsubscribeFromQueueResponse)(nil), // 7: rmqrpc.mockserver.api.v1.UnsubscribeFromQueueResponse
	(*GetAllSubscriptionsRequest)(nil),   // 8: rmqrpc.mockserver.api.v1.GetAllSubscriptionsRequest
	(*GetAllSubscriptionsResponse)(nil),  // 9: rmqrpc.mockserver.api.v1.GetAllSubscriptionsResponse
	(*JSONBodyAssertion)(nil),            // 10: rmqrpc.mockserver.api.v1.JSONBodyAssertion
	(*RegexBodyAssertion)(nil),           // 11: rmqrpc.mockserver.api.v1.RegexBodyAssertion
	(*Request)(nil),                      // 12: rmqrpc.mockserver.api.v1.Request
	(*Response)(nil),                     // 13: rmqrpc.mockserver.api.v1.Response
	(*Times)(nil),                        // 14: rmqrpc.mockserver.api.v1.Times
	(*CreateExpectationRequest)(nil),     // 15: rmqrpc.mockserver.api.v1.CreateExpectationRequest
	(*Expectation)(nil),                  // 16: rmqrpc.mockserver.api.v1.Expectation
	(*Assertion)(nil),                    // 17: rmqrpc.mockserver.api.v1.Assertion
	(*GetAssertionsRequest)(nil),         // 18: rmqrpc.mockserver.api.v1.GetAssertionsRequest
	(*GetAssertionsResponse)(nil),        // 19: rmqrpc.mockserver.api.v1.GetAssertionsResponse
	(*GetExpectationsRequest)(nil),       // 20: rmqrpc.mockserver.api.v1.GetExpectationsRequest
	(*GetExpectationsResponse)(nil),      // 21: rmqrpc.mockserver.api.v1.GetExpectationsResponse
	(*GetExpectationRequest)(nil),        // 22: rmqrpc.mockserver.api.v1.GetExpectationRequest
	(*GetExpectationResponse)(nil),       // 23: rmqrpc.mockserver.api.v1.GetExpectationResponse
	(*CreateExpectationResponse)(nil),    // 24: rmqrpc.mockserver.api.v1.CreateExpectationResponse
	(*ResetExpectationsRequest)(nil),     // 25: rmqrpc.mockserver.api.v1.ResetExpectationsRequest
	(*ResetExpectationsResponse)(nil),    // 26: rmqrpc.mockserver.api.v1.ResetExpectationsResponse
	(*ResetSubscriptionsRequest)(nil),    // 27: rmqrpc.mockserver.api.v1.ResetSubscriptionsRequest
	(*ResetSubscriptionsResponse)(nil),   // 28: rmqrpc.mockserver.api.v1.ResetSubscriptionsResponse
	(*ResetAllRequest)(nil),              // 29: rmqrpc.mockserver.api.v1.ResetAllRequest
	(*ResetAllResponse)(nil),             // 30: rmqrpc.mockserver.api.v1.ResetAllResponse
	(*GetVersionRequest)(nil),            // 31: rmqrpc.mockserver.api.v1.GetVersionRequest
	(*GetVersionResponse)(nil),           // 32: rmqrpc.mockserver.api.v1.GetVersionResponse
	(*Assertion_Candidate)(nil),          // 33: rmqrpc.mockserver.api.v1.Assertion.Candidate
	(*structpb.Struct)(nil),              // 34: google.protobuf.Struct
	(*structpb.Value)(nil),               // 35: google.protobuf.Value
}
var file_mockserver_proto_depIdxs = []int32{
	1,  // 0: rmqrpc.mockserver.api.v1.AddSubscriptionResponse.subscription:type_name -> rmqrpc.mockserver.api.v1.Subscription
	1,  // 1: rmqrpc.mockserver.api.v1.GetAllSubscriptionsResponse.subscriptions:type_name -> rmqrpc.mockserver.api.v1.Subscription
	34, // 2: rmqrpc.mockserver.api.v1.JSONBodyAssertion.body:type_name -> google.protobuf.Struct
	0,  // 3: rmqrpc.mockserver.api.v1.JSONBodyAssertion.match_type:type_name -> rmqrpc.mockserver.api.v1.JSONBodyAssertion.MatchType
	10, // 4: rmqrpc.mockserver.api.v1.Request.json_body:type_name -> rmqrpc.mockserver.api.v1.JSONBodyAssertion
	11, // 5: rmqrpc.mockserver.api.v1.Request.regex_body:type_name -> rmqrpc.mockserver.api.v1.RegexBodyAssertion
	35, // 6: rmqrpc.mockserver.api.v1.Response.body:type_name -> google.protobuf.Value
	12, // 7: rmqrpc.mockserver.api.v1.CreateExpectationRequest.request:type_name -> rmqrpc.mockserver.api.v1.Request
	13, // 8: rmqrpc.mockserver.api.v1.CreateExpectationRequest.response:type_name -> rmqrpc.mockserver.api.v1.Response
	14, // 9: rmqrpc.mockserver.api.v1.CreateExpectationRequest.times:type_name -> rmqrpc.mockserver.api.v1.Times
	12, // 10: rmqrpc.mockserver.api.v1.Expectation.request:type_name -> rmqrpc.mockserver.api.v1.Request
	13, // 11: rmqrpc.mockserver.api.v1.Expectation.response:type_name -> rmqrpc.mockserver.api.v1.Response
	14, // 12: rmqrpc.mockserver.api.v1.Expectation.times:type_name -> rmqrpc.mockserver.api.v1.Times
	33, // 13: rmqrpc.mockserver.api.v1.Assertion.candidate:type_name -> rmqrpc.mockserver.api.v1.Assertion.Candidate
	16, // 14: rmqrpc.mockserver.api.v1.Assertion.expectation:type_name -> rmqrpc.mockserver.api.v1.Expectation
	17, // 15: rmqrpc.mockserver.api.v1.GetAssertionsResponse.assertions:type_name -> rmqrpc.mockserver.api.v1.Assertion
	16, // 16: rmqrpc.mockserver.api.v1.GetExpectationsResponse.expectations:type_name -> rmqrpc.mockserver.api.v1.Expectation
	16, // 17: rmqrpc.mockserver.api.v1.GetExpectationResponse.expectation:type_name -> rmqrpc.mockserver.api.v1.Expectation
	34, // 18: rmqrpc.mockserver.api.v1.Assertion.Candidate.body:type_name -> google.protobuf.Struct
	15, // 19: rmqrpc.mockserver.api.v1.AmqpMockServerService.CreateExpectation:input_type -> rmqrpc.mockserver.api.v1.CreateExpectationRequest
	18, // 20: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetAssertions:input_type -> rmqrpc.mockserver.api.v1.GetAssertionsRequest
	20, // 21: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetExpectations:input_type -> rmqrpc.mockserver.api.v1.GetExpectationsRequest
	22, // 22: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetExpectation:input_type -> rmqrpc.mockserver.api.v1.GetExpectationRequest
	25, // 23: rmqrpc.mockserver.api.v1.AmqpMockServerService.ResetExpectations:input_type -> rmqrpc.mockserver.api.v1.ResetExpectationsRequest
	2,  // 24: rmqrpc.mockserver.api.v1.AmqpMockServerService.AddSubscription:input_type -> rmqrpc.mockserver.api.v1.AddSubscriptionRequest
	4,  // 25: rmqrpc.mockserver.api.v1.AmqpMockServerService.DeleteSubscription:input_type -> rmqrpc.mockserver.api.v1.DeleteSubscriptionRequest
	6,  // 26: rmqrpc.mockserver.api.v1.AmqpMockServerService.UnsubscribeFromQueue:input_type -> rmqrpc.mockserver.api.v1.UnsubscribeFromQueueRequest
	8,  // 27: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetAllSubscriptions:input_type -> rmqrpc.mockserver.api.v1.GetAllSubscriptionsRequest
	27, // 28: rmqrpc.mockserver.api.v1.AmqpMockServerService.ResetSubscriptions:input_type -> rmqrpc.mockserver.api.v1.ResetSubscriptionsRequest
	29, // 29: rmqrpc.mockserver.api.v1.AmqpMockServerService.ResetAll:input_type -> rmqrpc.mockserver.api.v1.ResetAllRequest
	31, // 30: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetVersion:input_type -> rmqrpc.mockserver.api.v1.GetVersionRequest
	24, // 31: rmqrpc.mockserver.api.v1.AmqpMockServerService.CreateExpectation:output_type -> rmqrpc.mockserver.api.v1.CreateExpectationResponse
	19, // 32: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetAssertions:output_type -> rmqrpc.mockserver.api.v1.GetAssertionsResponse
	21, // 33: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetExpectations:output_type -> rmqrpc.mockserver.api.v1.GetExpectationsResponse
	23, // 34: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetExpectation:output_type -> rmqrpc.mockserver.api.v1.GetExpectationResponse
	26, // 35: rmqrpc.mockserver.api.v1.AmqpMockServerService.ResetExpectations:output_type -> rmqrpc.mockserver.api.v1.ResetExpectationsResponse
	3,  // 36: rmqrpc.mockserver.api.v1.AmqpMockServerService.AddSubscription:output_type -> rmqrpc.mockserver.api.v1.AddSubscriptionResponse
	5,  // 37: rmqrpc.mockserver.api.v1.AmqpMockServerService.DeleteSubscription:output_type -> rmqrpc.mockserver.api.v1.DeleteSubscriptionResponse
	7,  // 38: rmqrpc.mockserver.api.v1.AmqpMockServerService.UnsubscribeFromQueue:output_type -> rmqrpc.mockserver.api.v1.UnsubscribeFromQueueResponse
	9,  // 39: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetAllSubscriptions:output_type -> rmqrpc.mockserver.api.v1.GetAllSubscriptionsResponse
	28, // 40: rmqrpc.mockserver.api.v1.AmqpMockServerService.ResetSubscriptions:output_type -> rmqrpc.mockserver.api.v1.ResetSubscriptionsResponse
	30, // 41: rmqrpc.mockserver.api.v1.AmqpMockServerService.ResetAll:output_type -> rmqrpc.mockserver.api.v1.ResetAllResponse
	32, // 42: rmqrpc.mockserver.api.v1.AmqpMockServerService.GetVersion:output_type -> rmqrpc.mockserver.api.v1.GetVersionResponse
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_mockserver_proto_init() }
func file_mockserver_proto_init() {
	if File_mockserver_proto != nil {
		return
	}
	file_mockserver_proto_msgTypes[11].OneofWrappers = []any{
		(*Request_JsonBody)(nil),
		(*Request_RegexBody)(nil),
	}
	file_mockserver_proto_msgTypes[13].OneofWrappers = []any{
		(*Times_RemainingTimes)(nil),
		(*Times_Unlimited)(nil),
	}
	file_mockserver_proto_msgTypes[14].OneofWrappers = []any{}
	file_mockserver_proto_msgTypes[15].OneofWrappers = []any{}
	file_mockserver_proto_msgTypes[16].OneofWrappers = []any{}
	file_mockserver_proto_msgTypes[17].OneofWrappers = []any{}
	file_mockserver_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mockserver_proto_rawDesc), len(file_mockserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mockserver_proto_goTypes,
		DependencyIndexes: file_mockserver_proto_depIdxs,
		EnumInfos:         file_mockserver_proto_enumTypes,
		MessageInfos:      file_mockserver_proto_msgTypes,
	}.Build()
	File_mockserver_proto = out.File
	file_mockserver_proto_goTypes = nil
	file_mockserver_proto_depIdxs = nil
}
